/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerInfo"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LinkLoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountSnapshot"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstrumentInfo"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/instruments/{symbol}/point-value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PointValue"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SymbolPrice"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/candles/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    timeframe: components["schemas"]["Timeframe"];
                    count?: number;
                };
                header?: never;
                path: {
                    accountId: string;
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candle"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    after?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventEnvelope"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlaceOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/positions/{positionId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    positionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/positions/{positionId}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    positionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ModifyStopsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    email?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/v1/users/{userId}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetPasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/v1/users/{userId}/login-links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": null | components["schemas"]["CreateLoginLinkRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginLinkResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAccountRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/v1/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountSnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/v1/accounts/{accountId}/floors/{floorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    floorId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetFloorRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    floorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/v1/accounts/{accountId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/v1/accounts/{accountId}/balance-operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BalanceOperationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    after?: number;
                    limit?: number;
                    wait?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FirmEventsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner/v1/server-names/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerNameResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTenantRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatedTenantResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner/v1/tenants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TenantResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partner/v1/tenants/{id}/admin-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminApiKeyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Account state valued at the latest prices. Amounts are in account currency. */
        AccountSnapshot: {
            accountId: string;
            groupId: string;
            currency: string;
            status: components["schemas"]["AccountStatus"];
            /** Format: double */
            balance: number;
            /** Format: double */
            equity: number;
            /** Format: double */
            usedMargin: number;
            /** Format: double */
            freeMargin: number;
            /** Format: double */
            marginLevelPercent: null | number;
            positions: components["schemas"]["PositionSnapshot"][];
            orders: components["schemas"]["OrderSnapshot"][];
            floors: components["schemas"]["FloorSnapshot"][];
        };
        /** @enum {unknown} */
        AccountStatus: "Active" | "Disabled";
        AdminApiKeyResponse: {
            adminApiKey: string;
        };
        /**
         * @description Deposits a positive Amount or withdraws a negative one. The caller chooses
         *     OperationId, unique per account, so a retry is answered 409 instead of being applied
         *     twice. A withdrawal must leave at least MinBalance.
         */
        BalanceOperationRequest: {
            operationId: null | string;
            /** Format: double */
            amount: number;
            /** Format: double */
            minBalance?: null | number;
        };
        /** @enum {unknown} */
        CancelReason: "Manual" | "InsufficientMargin" | "EquityFloor" | "AccountClosed";
        /** @description Bar of bid prices. Time is the start of the bar in UTC. */
        Candle: {
            /** Format: date-time */
            time: string;
            /** Format: double */
            open: number;
            /** Format: double */
            high: number;
            /** Format: double */
            low: number;
            /** Format: double */
            close: number;
            /** Format: int32 */
            tickCount: number;
        };
        /** @enum {unknown} */
        CloseReason: "Manual" | "StopLoss" | "TakeProfit" | "StopOut" | "EquityFloor" | "AccountClosed";
        /** @description The events a command caused, in order. */
        CommandResponse: {
            events: components["schemas"]["EventEnvelope"][];
        };
        /** @description Creates a trading account owned by a user of the same firm. */
        CreateAccountRequest: {
            accountId: string;
            groupId: string;
            /** Format: double */
            initialBalance: number;
            /** Format: uuid */
            ownerUserId: string;
        };
        /** @description A new firm, with the key to its admin API. The key is shown only once. */
        CreatedTenantResponse: {
            id: string;
            name: string;
            listed: boolean;
            groups: components["schemas"]["TenantGroupResponse"][];
            adminApiKey: string;
        };
        /** @description A login link for the user. With an account id, the terminal opens that account. */
        CreateLoginLinkRequest: {
            accountId: null | string;
        };
        /** @description A firm with its server Id, which traders log in to, and its name. */
        CreateTenantRequest: {
            id: null | string;
            name: null | string;
        };
        CreateUserRequest: {
            email: null | string;
            password: null | string;
        };
        /** @enum {unknown} */
        DisableReason: "EquityFloor" | "Closed";
        /** @description Output from the engine. The timestamp is the timestamp of the input that caused it. */
        EngineEvent: components["schemas"]["EngineEventAccountCreated"] | components["schemas"]["EngineEventAccountDisabled"] | components["schemas"]["EngineEventBalanceAdjusted"] | components["schemas"]["EngineEventEquityFloorBreached"] | components["schemas"]["EngineEventEquityFloorRemoved"] | components["schemas"]["EngineEventEquityFloorSet"] | components["schemas"]["EngineEventGroupCreated"] | components["schemas"]["EngineEventInputRejected"] | components["schemas"]["EngineEventOrderCancelled"] | components["schemas"]["EngineEventOrderPlaced"] | components["schemas"]["EngineEventPositionClosed"] | components["schemas"]["EngineEventPositionModified"] | components["schemas"]["EngineEventPositionOpened"] | components["schemas"]["EngineEventStopOutTriggered"];
        EngineEventAccountCreated: {
            /** @enum {string} */
            kind?: "AccountCreated";
            accountId: string;
            groupId: string;
            currency: string;
            /** Format: double */
            balance: number;
            /** Format: date-time */
            timestamp: string;
        };
        EngineEventAccountDisabled: {
            /** @enum {string} */
            kind?: "AccountDisabled";
            accountId: string;
            reason: components["schemas"]["DisableReason"];
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Money was deposited (positive amount) or withdrawn (negative amount). Not a trading result. */
        EngineEventBalanceAdjusted: {
            /** @enum {string} */
            kind?: "BalanceAdjusted";
            accountId: string;
            operationId: string;
            /** Format: double */
            amount: number;
            /** Format: double */
            balanceAfter: number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Equity fell below a floor. Holds the evidence at the moment of the breach, before positions are closed. */
        EngineEventEquityFloorBreached: {
            /** @enum {string} */
            kind?: "EquityFloorBreached";
            accountId: string;
            floorId: string;
            /** Format: double */
            level: number;
            /** Format: double */
            equity: number;
            prices: components["schemas"]["SymbolPrice"][];
            positions: components["schemas"]["PositionSnapshot"][];
            /** Format: date-time */
            timestamp: string;
        };
        EngineEventEquityFloorRemoved: {
            /** @enum {string} */
            kind?: "EquityFloorRemoved";
            accountId: string;
            floorId: string;
            /** Format: date-time */
            timestamp: string;
        };
        EngineEventEquityFloorSet: {
            /** @enum {string} */
            kind?: "EquityFloorSet";
            accountId: string;
            floorId: string;
            rule: components["schemas"]["EquityFloorRule"];
            /** Format: double */
            level: number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description A trading group was created. Its symbols are in symbol order. */
        EngineEventGroupCreated: {
            /** @enum {string} */
            kind?: "GroupCreated";
            group: components["schemas"]["TradingGroup"];
            /** Format: date-time */
            timestamp: string;
        };
        EngineEventInputRejected: {
            /** @enum {string} */
            kind?: "InputRejected";
            input: components["schemas"]["EngineInput"];
            reason: components["schemas"]["RejectReason"];
            /** Format: date-time */
            timestamp: string;
        };
        EngineEventOrderCancelled: {
            /** @enum {string} */
            kind?: "OrderCancelled";
            accountId: string;
            orderId: string;
            reason: components["schemas"]["CancelReason"];
            /** Format: date-time */
            timestamp: string;
        };
        /** @description A limit or stop order was accepted and waits for its price. */
        EngineEventOrderPlaced: {
            /** @enum {string} */
            kind?: "OrderPlaced";
            accountId: string;
            orderId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            type: components["schemas"]["OrderType"];
            /** Format: double */
            volume: number;
            /** Format: double */
            price: number;
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description A position was closed. Profit and commission are in account currency. */
        EngineEventPositionClosed: {
            /** @enum {string} */
            kind?: "PositionClosed";
            accountId: string;
            positionId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            /** Format: double */
            volume: number;
            /** Format: double */
            openPrice: number;
            /** Format: double */
            closePrice: number;
            /** Format: double */
            profit: number;
            /** Format: double */
            commission: number;
            reason: components["schemas"]["CloseReason"];
            /** Format: double */
            balanceAfter: number;
            /** Format: date-time */
            timestamp: string;
        };
        EngineEventPositionModified: {
            /** @enum {string} */
            kind?: "PositionModified";
            accountId: string;
            positionId: string;
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description A position was opened. The position id is the id of the order that opened it. */
        EngineEventPositionOpened: {
            /** @enum {string} */
            kind?: "PositionOpened";
            accountId: string;
            positionId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            /** Format: double */
            volume: number;
            /** Format: double */
            openPrice: number;
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
            /** Format: double */
            commission: number;
            /** Format: double */
            balanceAfter: number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description The margin level fell below the stop out level. Positions are closed, largest loss first. */
        EngineEventStopOutTriggered: {
            /** @enum {string} */
            kind?: "StopOutTriggered";
            accountId: string;
            /** Format: double */
            equity: number;
            /** Format: double */
            usedMargin: number;
            /** Format: double */
            marginLevelPercent: number;
            /** Format: date-time */
            timestamp: string;
        };
        /**
         * @description Input to the engine. The timestamp is set by the service when the input arrives
         *     and must never be earlier than the previous input.
         */
        EngineInput: components["schemas"]["EngineInputAdjustBalance"] | components["schemas"]["EngineInputCancelOrder"] | components["schemas"]["EngineInputCloseAccount"] | components["schemas"]["EngineInputClosePosition"] | components["schemas"]["EngineInputCreateAccount"] | components["schemas"]["EngineInputCreateGroup"] | components["schemas"]["EngineInputModifyPosition"] | components["schemas"]["EngineInputPlaceOrder"] | components["schemas"]["EngineInputQuote"] | components["schemas"]["EngineInputRemoveEquityFloor"] | components["schemas"]["EngineInputSetEquityFloor"];
        /**
         * @description Deposits a positive Amount or withdraws a negative one. The caller chooses
         *     OperationId, which is never reused on the account, so a retry cannot apply it twice.
         *     A withdrawal must leave the balance at or above MinBalance, fit in the free margin
         *     and keep equity above every floor.
         */
        EngineInputAdjustBalance: {
            /** @enum {string} */
            kind?: "AdjustBalance";
            accountId: string;
            operationId: string;
            /** Format: double */
            amount: number;
            /** Format: double */
            minBalance?: null | number;
            /** Format: date-time */
            timestamp: string;
        };
        EngineInputCancelOrder: {
            /** @enum {string} */
            kind?: "CancelOrder";
            accountId: string;
            orderId: string;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Closes all positions at the latest prices, cancels all orders and disables the account. */
        EngineInputCloseAccount: {
            /** @enum {string} */
            kind?: "CloseAccount";
            accountId: string;
            /** Format: date-time */
            timestamp: string;
        };
        EngineInputClosePosition: {
            /** @enum {string} */
            kind?: "ClosePosition";
            accountId: string;
            positionId: string;
            /** Format: date-time */
            timestamp: string;
        };
        EngineInputCreateAccount: {
            /** @enum {string} */
            kind?: "CreateAccount";
            accountId: string;
            groupId: string;
            /** Format: double */
            initialBalance: number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Creates a trading group, for example for a firm that signed up. Its conditions never change afterwards. */
        EngineInputCreateGroup: {
            /** @enum {string} */
            kind?: "CreateGroup";
            group: components["schemas"]["TradingGroup"];
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Sets stop loss and take profit. An empty value removes it. */
        EngineInputModifyPosition: {
            /** @enum {string} */
            kind?: "ModifyPosition";
            accountId: string;
            positionId: string;
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Places an order. Price is required for limit and stop orders and must be empty for market orders. */
        EngineInputPlaceOrder: {
            /** @enum {string} */
            kind?: "PlaceOrder";
            accountId: string;
            orderId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            type: components["schemas"]["OrderType"];
            /** Format: double */
            volume: number;
            /** Format: double */
            price?: null | number;
            /** Format: double */
            stopLoss?: null | number;
            /** Format: double */
            takeProfit?: null | number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Raw price from the feed, before spread markup. */
        EngineInputQuote: {
            /** @enum {string} */
            kind?: "Quote";
            symbol: string;
            /** Format: double */
            bid: number;
            /** Format: double */
            ask: number;
            /** Format: date-time */
            timestamp: string;
        };
        EngineInputRemoveEquityFloor: {
            /** @enum {string} */
            kind?: "RemoveEquityFloor";
            accountId: string;
            floorId: string;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Adds or replaces a named equity floor on the account. */
        EngineInputSetEquityFloor: {
            /** @enum {string} */
            kind?: "SetEquityFloor";
            accountId: string;
            floorId: string;
            rule: components["schemas"]["EquityFloorRule"];
            /** Format: date-time */
            timestamp: string;
        };
        /**
         * @description Rule for an equity floor. When equity falls below the floor, all positions are closed,
         *     all pending orders are cancelled and the account is disabled.
         */
        EquityFloorRule: components["schemas"]["EquityFloorRuleAnchoredFloor"] | components["schemas"]["EquityFloorRuleFixedFloor"] | components["schemas"]["EquityFloorRuleTrailingFloor"];
        /**
         * @description A floor Distance below the account as it is when the floor is set: its balance, or
         *     the higher of balance and equity. The level then stays fixed. Setting it again at the start of every
         *     trading day gives a daily loss limit, with the level taken in the same step as the prices.
         */
        EquityFloorRuleAnchoredFloor: {
            /** @enum {string} */
            kind?: "AnchoredFloor";
            /** Format: double */
            distance: number;
            anchor: components["schemas"]["FloorAnchor"];
        };
        /** @description A fixed floor in account currency. */
        EquityFloorRuleFixedFloor: {
            /** @enum {string} */
            kind?: "FixedFloor";
            /** Format: double */
            level: number;
        };
        /** @description A floor that trails the highest observed equity by Distance and stops rising at LockLevel. */
        EquityFloorRuleTrailingFloor: {
            /** @enum {string} */
            kind?: "TrailingFloor";
            /** Format: double */
            distance: number;
            /** Format: double */
            lockLevel?: null | number;
        };
        /** @description An engine event with a sequence number that orders all events in the service. */
        EventEnvelope: {
            /** Format: int64 */
            sequence: number;
            event: components["schemas"]["EngineEvent"];
        };
        /** @description The firm's events in order. Ask again with `after` set to Cursor for the next ones. */
        FirmEventsResponse: {
            events: components["schemas"]["EventEnvelope"][];
            /** Format: int64 */
            cursor: number;
        };
        /**
         * @description What an AnchoredFloor is measured from when it is set.
         * @enum {unknown}
         */
        FloorAnchor: "Balance" | "HigherOfBalanceAndEquity";
        /** @description An equity floor. Headroom is how far equity can fall before the floor is breached. */
        FloorSnapshot: {
            floorId: string;
            rule: components["schemas"]["EquityFloorRule"];
            /** Format: double */
            level: number;
            /** Format: double */
            highWaterMark: number;
            /** Format: double */
            headroom: number;
        };
        /** @description An instrument as one group trades it. */
        InstrumentInfo: {
            symbol: string;
            baseCurrency: string;
            quoteCurrency: string;
            /** Format: double */
            contractSize: number;
            /** Format: int32 */
            digits: number;
            /** Format: double */
            volumeMin: number;
            /** Format: double */
            volumeStep: number;
            /** Format: double */
            volumeMax: number;
            /** Format: int32 */
            leverage: number;
            /** Format: int32 */
            spreadMarkupPoints: number;
            /** Format: double */
            commissionPerLotPerSide: number;
        };
        /** @description The token from a login link. */
        LinkLoginRequest: {
            token: null | string;
        };
        /** @description Open Url once before ExpiresAt to be logged in to the terminal. */
        LoginLinkResponse: {
            /** Format: uri */
            url: string;
            /** Format: date-time */
            expiresAt: string;
        };
        /** @description Server is the id of the firm's server, as in MetaTrader. */
        LoginRequest: {
            server: null | string;
            email: null | string;
            password: null | string;
        };
        /** @description The logged in trader, their firm's server and the accounts they own. */
        MeResponse: {
            /** Format: uuid */
            userId: string;
            email: string;
            server: components["schemas"]["ServerInfo"];
            accounts: string[];
        };
        ModifyStopsRequest: {
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
        };
        OrderSnapshot: {
            orderId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            type: components["schemas"]["OrderType"];
            /** Format: double */
            volume: number;
            /** Format: double */
            price: number;
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
            /** Format: date-time */
            placedTime: string;
        };
        /** @enum {unknown} */
        OrderType: "Market" | "Limit" | "Stop";
        /** @description Places an order. The client creates the order id, so a retry can never place the order twice. */
        PlaceOrderRequest: {
            orderId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            type: components["schemas"]["OrderType"];
            /** Format: double */
            volume: number;
            /** Format: double */
            price?: null | number;
            /** Format: double */
            stopLoss?: null | number;
            /** Format: double */
            takeProfit?: null | number;
        };
        /**
         * @description What a one point move on one lot of the symbol is worth in the account currency, at the latest conversion rate.
         *     Profit is points times volume times PerLot, before rounding and commission.
         */
        PointValue: {
            symbol: string;
            currency: string;
            /** Format: double */
            perLot: number;
        };
        /** @description An open position. CurrentPrice is the price it would close at now. */
        PositionSnapshot: {
            positionId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            /** Format: double */
            volume: number;
            /** Format: double */
            openPrice: number;
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
            /** Format: date-time */
            openTime: string;
            /** Format: double */
            currentPrice: number;
            /** Format: double */
            profit: number;
            /** Format: double */
            margin: number;
        };
        /** @enum {unknown} */
        RejectReason: "OutOfOrder" | "InvalidId" | "DuplicateId" | "UnknownSymbol" | "InvalidQuote" | "UnknownGroup" | "InvalidGroup" | "InvalidAmount" | "UnknownAccount" | "AccountDisabled" | "SymbolNotTradable" | "InvalidOrder" | "InvalidVolume" | "InvalidPrice" | "InvalidStopLoss" | "InvalidTakeProfit" | "NoPrice" | "StalePrice" | "NoConversionRate" | "InsufficientMargin" | "UnknownOrder" | "UnknownPosition" | "InvalidFloor" | "UnknownFloor" | "InsufficientFunds";
        /** @description A firm's server: the id traders log in with and the firm's name. */
        ServerInfo: {
            id: string;
            name: string;
        };
        ServerNameResponse: {
            id: string;
            available: boolean;
        };
        SetFloorRequest: {
            rule: components["schemas"]["EquityFloorRule"];
        };
        SetPasswordRequest: {
            password: null | string;
        };
        /** @enum {unknown} */
        Side: "Buy" | "Sell";
        /** @description Conditions for one symbol within a group. */
        SymbolConditions: {
            symbol: string;
            /**
             * Format: int32
             * @description Margin is the position value divided by this.
             */
            leverage: number;
            /**
             * Format: int32
             * @description Points added to the raw spread. The bid is lowered by half, rounded down, and the ask raised by the rest.
             */
            spreadMarkupPoints: number;
            /**
             * Format: double
             * @description Commission in account currency, charged both on open and on close.
             */
            commissionPerLotPerSide: number;
            /**
             * Format: int32
             * @description Points the bid is lowered by.
             */
            bidMarkupPoints?: number;
            /**
             * Format: int32
             * @description Points the ask is raised by.
             */
            askMarkupPoints?: number;
        };
        /** @description Price after the group's spread markup, with the time the raw price arrived. */
        SymbolPrice: {
            symbol: string;
            /** Format: double */
            bid: number;
            /** Format: double */
            ask: number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description A firm's trading group and its account currency. */
        TenantGroupResponse: {
            id: string;
            currency: string;
        };
        /** @description A firm. Only Listed servers are on the list traders choose from. */
        TenantResponse: {
            id: string;
            name: string;
            listed: boolean;
            groups: components["schemas"]["TenantGroupResponse"][];
        };
        /** @enum {unknown} */
        Timeframe: "M1" | "M5" | "M15" | "M30" | "H1" | "H4" | "D1";
        /** @description Trading conditions shared by a group of accounts, set by the firm. */
        TradingGroup: {
            id: string;
            /** @description Account currency for all accounts in the group. */
            currency: string;
            /**
             * Format: double
             * @description Positions are closed when the margin level falls below this. 0 disables stop out.
             */
            stopOutLevelPercent: number;
            /** @description The symbols the group may trade, with their conditions. */
            symbols: components["schemas"]["SymbolConditions"][];
        };
        UserResponse: {
            /** Format: uuid */
            userId: string;
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
