/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountSnapshot"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstrumentInfo"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SymbolPrice"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/candles/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    timeframe: components["schemas"]["Timeframe"];
                    count?: number;
                };
                header?: never;
                path: {
                    accountId: string;
                    symbol: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Candle"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    after?: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventEnvelope"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlaceOrderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    orderId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/positions/{positionId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    positionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/positions/{positionId}/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    positionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ModifyStopsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAccountRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts/{accountId}/floors/{floorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    floorId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetFloorRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                    floorId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts/{accountId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommandResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Account state valued at the latest prices. Amounts are in account currency. */
        AccountSnapshot: {
            accountId: string;
            groupId: string;
            currency: string;
            status: components["schemas"]["AccountStatus"];
            /** Format: double */
            balance: number;
            /** Format: double */
            equity: number;
            /** Format: double */
            usedMargin: number;
            /** Format: double */
            freeMargin: number;
            /** Format: double */
            marginLevelPercent: null | number;
            positions: components["schemas"]["PositionSnapshot"][];
            orders: components["schemas"]["OrderSnapshot"][];
            floors: components["schemas"]["FloorSnapshot"][];
        };
        /** @enum {unknown} */
        AccountStatus: "Active" | "Disabled";
        /** @enum {unknown} */
        CancelReason: "Manual" | "InsufficientMargin" | "EquityFloor" | "AccountClosed";
        /** @description Bar of bid prices. Time is the start of the bar in UTC. */
        Candle: {
            /** Format: date-time */
            time: string;
            /** Format: double */
            open: number;
            /** Format: double */
            high: number;
            /** Format: double */
            low: number;
            /** Format: double */
            close: number;
            /** Format: int32 */
            tickCount: number;
        };
        /** @enum {unknown} */
        CloseReason: "Manual" | "StopLoss" | "TakeProfit" | "StopOut" | "EquityFloor" | "AccountClosed";
        /** @description The events a command caused, in order. */
        CommandResponse: {
            events: components["schemas"]["EventEnvelope"][];
        };
        CreateAccountRequest: {
            accountId: string;
            groupId: string;
            /** Format: double */
            initialBalance: number;
        };
        /** @enum {unknown} */
        DisableReason: "EquityFloor" | "Closed";
        /** @description Output from the engine. The timestamp is the timestamp of the input that caused it. */
        EngineEvent: components["schemas"]["EngineEventAccountCreated"] | components["schemas"]["EngineEventAccountDisabled"] | components["schemas"]["EngineEventEquityFloorBreached"] | components["schemas"]["EngineEventEquityFloorRemoved"] | components["schemas"]["EngineEventEquityFloorSet"] | components["schemas"]["EngineEventInputRejected"] | components["schemas"]["EngineEventOrderCancelled"] | components["schemas"]["EngineEventOrderPlaced"] | components["schemas"]["EngineEventPositionClosed"] | components["schemas"]["EngineEventPositionModified"] | components["schemas"]["EngineEventPositionOpened"] | components["schemas"]["EngineEventStopOutTriggered"];
        EngineEventAccountCreated: {
            /** @enum {string} */
            kind?: "AccountCreated";
            accountId: string;
            groupId: string;
            currency: string;
            /** Format: double */
            balance: number;
            /** Format: date-time */
            timestamp: string;
        };
        EngineEventAccountDisabled: {
            /** @enum {string} */
            kind?: "AccountDisabled";
            accountId: string;
            reason: components["schemas"]["DisableReason"];
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Equity fell below a floor. Holds the evidence at the moment of the breach, before positions are closed. */
        EngineEventEquityFloorBreached: {
            /** @enum {string} */
            kind?: "EquityFloorBreached";
            accountId: string;
            floorId: string;
            /** Format: double */
            level: number;
            /** Format: double */
            equity: number;
            prices: components["schemas"]["SymbolPrice"][];
            positions: components["schemas"]["PositionSnapshot"][];
            /** Format: date-time */
            timestamp: string;
        };
        EngineEventEquityFloorRemoved: {
            /** @enum {string} */
            kind?: "EquityFloorRemoved";
            accountId: string;
            floorId: string;
            /** Format: date-time */
            timestamp: string;
        };
        EngineEventEquityFloorSet: {
            /** @enum {string} */
            kind?: "EquityFloorSet";
            accountId: string;
            floorId: string;
            rule: components["schemas"]["EquityFloorRule"];
            /** Format: double */
            level: number;
            /** Format: date-time */
            timestamp: string;
        };
        EngineEventInputRejected: {
            /** @enum {string} */
            kind?: "InputRejected";
            input: components["schemas"]["EngineInput"];
            reason: components["schemas"]["RejectReason"];
            /** Format: date-time */
            timestamp: string;
        };
        EngineEventOrderCancelled: {
            /** @enum {string} */
            kind?: "OrderCancelled";
            accountId: string;
            orderId: string;
            reason: components["schemas"]["CancelReason"];
            /** Format: date-time */
            timestamp: string;
        };
        /** @description A limit or stop order was accepted and waits for its price. */
        EngineEventOrderPlaced: {
            /** @enum {string} */
            kind?: "OrderPlaced";
            accountId: string;
            orderId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            type: components["schemas"]["OrderType"];
            /** Format: double */
            volume: number;
            /** Format: double */
            price: number;
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description A position was closed. Profit and commission are in account currency. */
        EngineEventPositionClosed: {
            /** @enum {string} */
            kind?: "PositionClosed";
            accountId: string;
            positionId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            /** Format: double */
            volume: number;
            /** Format: double */
            openPrice: number;
            /** Format: double */
            closePrice: number;
            /** Format: double */
            profit: number;
            /** Format: double */
            commission: number;
            reason: components["schemas"]["CloseReason"];
            /** Format: double */
            balanceAfter: number;
            /** Format: date-time */
            timestamp: string;
        };
        EngineEventPositionModified: {
            /** @enum {string} */
            kind?: "PositionModified";
            accountId: string;
            positionId: string;
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description A position was opened. The position id is the id of the order that opened it. */
        EngineEventPositionOpened: {
            /** @enum {string} */
            kind?: "PositionOpened";
            accountId: string;
            positionId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            /** Format: double */
            volume: number;
            /** Format: double */
            openPrice: number;
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
            /** Format: double */
            commission: number;
            /** Format: double */
            balanceAfter: number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description The margin level fell below the stop out level. Positions are closed, largest loss first. */
        EngineEventStopOutTriggered: {
            /** @enum {string} */
            kind?: "StopOutTriggered";
            accountId: string;
            /** Format: double */
            equity: number;
            /** Format: double */
            usedMargin: number;
            /** Format: double */
            marginLevelPercent: number;
            /** Format: date-time */
            timestamp: string;
        };
        /**
         * @description Input to the engine. The timestamp is set by the service when the input arrives
         *     and must never be earlier than the previous input.
         */
        EngineInput: components["schemas"]["EngineInputCancelOrder"] | components["schemas"]["EngineInputCloseAccount"] | components["schemas"]["EngineInputClosePosition"] | components["schemas"]["EngineInputCreateAccount"] | components["schemas"]["EngineInputModifyPosition"] | components["schemas"]["EngineInputPlaceOrder"] | components["schemas"]["EngineInputQuote"] | components["schemas"]["EngineInputRemoveEquityFloor"] | components["schemas"]["EngineInputSetEquityFloor"];
        EngineInputCancelOrder: {
            /** @enum {string} */
            kind?: "CancelOrder";
            accountId: string;
            orderId: string;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Closes all positions at the latest prices, cancels all orders and disables the account. */
        EngineInputCloseAccount: {
            /** @enum {string} */
            kind?: "CloseAccount";
            accountId: string;
            /** Format: date-time */
            timestamp: string;
        };
        EngineInputClosePosition: {
            /** @enum {string} */
            kind?: "ClosePosition";
            accountId: string;
            positionId: string;
            /** Format: date-time */
            timestamp: string;
        };
        EngineInputCreateAccount: {
            /** @enum {string} */
            kind?: "CreateAccount";
            accountId: string;
            groupId: string;
            /** Format: double */
            initialBalance: number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Sets stop loss and take profit. An empty value removes it. */
        EngineInputModifyPosition: {
            /** @enum {string} */
            kind?: "ModifyPosition";
            accountId: string;
            positionId: string;
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Places an order. Price is required for limit and stop orders and must be empty for market orders. */
        EngineInputPlaceOrder: {
            /** @enum {string} */
            kind?: "PlaceOrder";
            accountId: string;
            orderId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            type: components["schemas"]["OrderType"];
            /** Format: double */
            volume: number;
            /** Format: double */
            price?: null | number;
            /** Format: double */
            stopLoss?: null | number;
            /** Format: double */
            takeProfit?: null | number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Raw price from the feed, before spread markup. */
        EngineInputQuote: {
            /** @enum {string} */
            kind?: "Quote";
            symbol: string;
            /** Format: double */
            bid: number;
            /** Format: double */
            ask: number;
            /** Format: date-time */
            timestamp: string;
        };
        EngineInputRemoveEquityFloor: {
            /** @enum {string} */
            kind?: "RemoveEquityFloor";
            accountId: string;
            floorId: string;
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Adds or replaces a named equity floor on the account. */
        EngineInputSetEquityFloor: {
            /** @enum {string} */
            kind?: "SetEquityFloor";
            accountId: string;
            floorId: string;
            rule: components["schemas"]["EquityFloorRule"];
            /** Format: date-time */
            timestamp: string;
        };
        /**
         * @description Rule for an equity floor. When equity falls below the floor, all positions are closed,
         *     all pending orders are cancelled and the account is disabled.
         */
        EquityFloorRule: components["schemas"]["EquityFloorRuleFixedFloor"] | components["schemas"]["EquityFloorRuleTrailingFloor"];
        /** @description A fixed floor in account currency. */
        EquityFloorRuleFixedFloor: {
            /** @enum {string} */
            kind?: "FixedFloor";
            /** Format: double */
            level: number;
        };
        /** @description A floor that trails the highest observed equity by Distance and stops rising at LockLevel. */
        EquityFloorRuleTrailingFloor: {
            /** @enum {string} */
            kind?: "TrailingFloor";
            /** Format: double */
            distance: number;
            /** Format: double */
            lockLevel?: null | number;
        };
        /** @description An engine event with a sequence number that orders all events in the service. */
        EventEnvelope: {
            /** Format: int64 */
            sequence: number;
            event: components["schemas"]["EngineEvent"];
        };
        /** @description An equity floor. Headroom is how far equity can fall before the floor is breached. */
        FloorSnapshot: {
            floorId: string;
            rule: components["schemas"]["EquityFloorRule"];
            /** Format: double */
            level: number;
            /** Format: double */
            highWaterMark: number;
            /** Format: double */
            headroom: number;
        };
        /** @description An instrument as one group trades it. */
        InstrumentInfo: {
            symbol: string;
            baseCurrency: string;
            quoteCurrency: string;
            /** Format: double */
            contractSize: number;
            /** Format: int32 */
            digits: number;
            /** Format: double */
            volumeMin: number;
            /** Format: double */
            volumeStep: number;
            /** Format: double */
            volumeMax: number;
            /** Format: int32 */
            leverage: number;
            /** Format: int32 */
            spreadMarkupPoints: number;
            /** Format: double */
            commissionPerLotPerSide: number;
        };
        ModifyStopsRequest: {
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
        };
        OrderSnapshot: {
            orderId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            type: components["schemas"]["OrderType"];
            /** Format: double */
            volume: number;
            /** Format: double */
            price: number;
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
            /** Format: date-time */
            placedTime: string;
        };
        /** @enum {unknown} */
        OrderType: "Market" | "Limit" | "Stop";
        /** @description Places an order. The client creates the order id, so a retry can never place the order twice. */
        PlaceOrderRequest: {
            orderId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            type: components["schemas"]["OrderType"];
            /** Format: double */
            volume: number;
            /** Format: double */
            price?: null | number;
            /** Format: double */
            stopLoss?: null | number;
            /** Format: double */
            takeProfit?: null | number;
        };
        /** @description An open position. CurrentPrice is the price it would close at now. */
        PositionSnapshot: {
            positionId: string;
            symbol: string;
            side: components["schemas"]["Side"];
            /** Format: double */
            volume: number;
            /** Format: double */
            openPrice: number;
            /** Format: double */
            stopLoss: null | number;
            /** Format: double */
            takeProfit: null | number;
            /** Format: date-time */
            openTime: string;
            /** Format: double */
            currentPrice: number;
            /** Format: double */
            profit: number;
            /** Format: double */
            margin: number;
        };
        /** @enum {unknown} */
        RejectReason: "OutOfOrder" | "InvalidId" | "DuplicateId" | "UnknownSymbol" | "InvalidQuote" | "UnknownGroup" | "InvalidAmount" | "UnknownAccount" | "AccountDisabled" | "SymbolNotTradable" | "InvalidOrder" | "InvalidVolume" | "InvalidPrice" | "InvalidStopLoss" | "InvalidTakeProfit" | "NoPrice" | "StalePrice" | "NoConversionRate" | "InsufficientMargin" | "UnknownOrder" | "UnknownPosition" | "InvalidFloor" | "UnknownFloor";
        SetFloorRequest: {
            rule: components["schemas"]["EquityFloorRule"];
        };
        /** @enum {unknown} */
        Side: "Buy" | "Sell";
        /** @description Price after the group's spread markup, with the time the raw price arrived. */
        SymbolPrice: {
            symbol: string;
            /** Format: double */
            bid: number;
            /** Format: double */
            ask: number;
            /** Format: date-time */
            timestamp: string;
        };
        /** @enum {unknown} */
        Timeframe: "M1" | "M5" | "M15" | "M30" | "H1" | "H4" | "D1";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
