<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Prop.Rules\Prop.Rules.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Golden\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
